name: Bug Report
description: File a report about somthing that went wrong.
title: "[Bug]: "
labels: ["bug", "triage"]
type: "Bug"
body:
  - type: markdown
    attributes:
      value: |
        Thank you for helping us improve. Please be direct, but polite :)

  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description:
        A short description on what the bug is.
      placeholder:
        My effort to fetch some bananas did give me fruits that I could not eat.
    validations:
      required: false

  - type: textarea
    id: happening
    attributes:
      label: What happened?
      description:
        Describe what happened. You may include error messages here.
      placeholder:
        When I tried to run `fetch banana --amount 3`, I notices that the **bananas** I got were still very much green (see *image_1.png*), indicating that they should not be eaten.
    validations:
      required: true

  - type: textarea
    id: expectation
    attributes:
      label: What should have happened?
      description:
        What did you expect to happen?
      placeholder:
        I just wanted some ripe bananas.
    validations:
      required: false

  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction of the problem
      description:
        What are steps for us to see what problem you are facing? In an ideal world you would provide a minimal example. You may also attach example data if necessary.
      placeholder:
        1. Install `banana-tree` via `planting`
        2. Run `fetch banana --amount 1` (produces same result)
        3. Inspect the color (my banana was close to \#51a03d)
    validations:
      required: false

  - type: input
    id: version-plugin
    attributes:
      label: nf-co2footprint plugin version
      description: |
        <details>
        <summary>How to get the plugin version:</summary>
          * Option 1: Report the version behind the `@` in following command. 
            * ```bash
              nextflow config | grep nf-co2footprint
              ```
          * Option 2: Run a small pipeline to get the version that is downloaded with no further specification.
            * ```bash
              nextflow run nextflow-io/hello -plugins nf-co2footprint | grep nf-co2footprint
              ```
        </details>
      placeholder:
        1.0.0-beta
    validations:
      required: false
